# -*- coding: utf-8 -*-
"""geolocation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eKU1LkGyNCo_zVoLmgKV--3j-c7DcAJq
"""

import pandas as pd
from geopy.geocoders import Nominatim
import urllib
import requests

from geopy.geocoders import Nominatim

df = pd.read_csv("master_for_sale.csv")

df['address']=df['Street Address']+' '+df['Suburb']+' '+df['State']

lats = []
longs = []
addresses = []

geolocator = Nominatim()

def get_nominatim_geocode(address):
    try:
      location = geolocator.geocode(address, timeout = 100000)
      return location.longitude, location.latitude
    except Exception as e:
        # print(e)
        return None, None

def get_positionstack_geocode(address):
  BASE_URL = "http://api.positionstack.com/v1/forward?access_key="
  API_KEY = "ENTER API KEY"
  
  url = BASE_URL +API_KEY+'&query='+urllib.parse.quote(address)
  try:
      response = requests.get(url).json()
      # print( response["data"][0])
      return response["data"][0]["longitude"], response["data"][0]["latitude"]
  except Exception as e:
      # print(e)
      return None,None

def get_geocode(address):
  long,lat = get_nominatim_geocode(address)
  if long == None:
    long,lat = get_positionstack_geocode(address)
    print(address, long, lat)
    addresses.append(address)
    lats.append(lat)
    longs.append(long)
  else:
    print(address, long, lat)
    addresses.append(address)
    lats.append(lat)
    longs.append(long)

for c in df.address:
  get_geocode(c)

result = pd.DataFrame()
result['Address'] = addresses
result['Latitude'] = lats
result['Longitude'] = longs

result.to_csv('Coordinates.csv', index = False)